### PR TITLE
Update savefile path and fix crash

### PR DESCRIPTION
**Pull request by RedoHeal**
Game Version 0.756.9

### CODE REVIEW

**Comment by LiquidBleh** [comment]
Never would have thought that there is some traffic here :D is assume you already built the project and it does work!?!

**Comment by RedoHeal** [comment]
Yess
I wanted to use the tool (thanks for that)
Then I had a crash on the first try
and I got to the bottom of it
(Wasn't a big mistake) =)

**Comment by LiquidBleh** [comment]
I saw you redirected the url to your own cheat table, which is fine i guess. Sure i will merge that.

**Comment by RedoHeal** [comment]
oh I just saw that my latest change was also applied..
I took the link from the CheatTable to my repository, bitte nicht verwundern! ^^'

Yes, I was about to write - I was probably too late!

**Comment by LiquidBleh** [comment]
you were completely right :D i have no plans to work any longer on that project, but i am glad that you can use it as foundation for your work. you can use it as you want.

**Comment by RedoHeal** [comment]
Thank you very much!
The current version works and I don't think it will stop working any time soon..
I will definitely continue to run the CheatTable.

**Pull request merged**
